ProjectFirma: Fixing crash on null Person here when anonymous user. This is probably leftover from Impersonation and the introduction of a nullable person.
Arguably we should be calling this on the Current Session rather than the Current Person, but I'll start with this to stop the immediate bleeding. I may do the further, deeper fix next.

2019-12-03 09:55:35,148;38;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProjectFirmaModels.Models.ProjectStewardshipAreaTypeProjectStewardingOrganizations.GetPersonStewardOrganizations(Person person) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirmaModels\Models\ProjectStewardshipAreaType.cs:line 32
   at ProjectFirmaModels.Models.ProjectStewardshipAreaTypeProjectStewardingOrganizations.CanStewardProject(Person person, Project project) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirmaModels\Models\ProjectStewardshipAreaType.cs:line 27
   at ProjectFirma.Web.Views.Project.DetailViewData..ctor(FirmaSession currentFirmaSession, Project project, List`1 projectStages, ProjectBasicsViewData projectBasicsViewData, ProjectLocationSummaryViewData projectLocationSummaryViewData, ProjectBudgetSummaryViewData projectBudgetSummaryViewData, ProjectBudgetsAnnualViewData projectBudgetsAnnualViewData, ProjectBudgetsAnnualByCostTypeViewData projectBudgetsAnnualByCostTypeViewData, TechnicalAssistanceRequestsDetailViewData technicalAssistanceRequestDetailViewData, PerformanceMeasureExpectedSummaryViewData performanceMeasureExpectedSummaryViewData, PerformanceMeasureReportedValuesGroupedViewData performanceMeasureReportedValuesGroupedViewData, ProjectExpendituresDetailViewData projectExpendituresDetailViewData, ProjectExpendituresByCostTypeDetailViewData projectExpendituresByCostTypeDetailViewData, ImageGalleryViewData imageGalleryViewData, EntityNotesViewData projectNotesViewData, EntityNotesViewData internalNotesViewData, EntityExternalLinksViewData entityExternalLinksViewData, ProjectBasicsTagsViewData projectBasicsTagsViewData, Boolean userHasProjectAdminPermissions, Boolean userHasEditProjectPermissions, Boolean userHasProjectUpdatePermissions, Boolean userHasPerformanceMeasureActualManagePermissions, String mapFormID, String editProjectCustomAttributesUrl, String editSimpleProjectLocationUrl, String editDetailedProjectLocationUrl, String editProjectOrganizationsUrl, String editPerformanceMeasureExpectedsUrl, String editPerformanceMeasureActualsUrl, String editReportedExpendituresUrl, Boolean reportFinancialsByCostType, AuditLogsGridSpec auditLogsGridSpec, String auditLogsGridDataUrl, String editExternalLinksUrl, ProjectNotificationGridSpec projectNotificationGridSpec, String projectNotificationGridName, String projectNotificationGridDataUrl, Boolean userCanEditProposal, ProjectOrganizationsDetailViewData projectOrganizationsDetailViewData, List`1 classificationSystems, String editProjectBoundingBoxFormID, List`1 geospatialAreaTypes, DisplayProjectCustomAttributesViewData displayProjectCustomAttributeTypesViewData, ProjectContactsDetailViewData projectContactsDetailViewData, String editProjectContactsUrl, String editExpectedFundingUrl, ProjectTimelineDisplayViewData projectTimelineDisplayViewData, Boolean userHasProjectTimelinePermissions) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Views\Project\DetailViewData.cs:line 268
   at ProjectFirma.Web.Controllers.ProjectController.Detail(ProjectPrimaryKey projectPrimaryKey) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\ProjectController.cs:line 217
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Anonymous

IP Address: 192.168.10.183
Hostname: stewart.sitka.local
Whois Info:
            NetRange:       192.168.0.0 - 192.168.255.255
            CIDR:           192.168.0.0/16
            NetName:        PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED
            NetHandle:      NET-192-168-0-0-1
            Parent:         NET192 (NET-192-0-0-0-0)
            NetType:        IANA Special Use
            OriginAS:
            Organization:   Internet Assigned Numbers Authority (IANA)
            RegDate:        1994-03-15
            Updated:        2013-08-30
            Comment:        These addresses are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
            Comment:
            Comment:        These addresses can be used by anyone without any need to coordinate with IANA or an Internet registry.  The traffic from these addresses does not come from ICANN or IANA.  We are not the source of activity you may see on logs or in e-mail records.  Please refer to http://www.iana.org/abuse/answers
            Comment:
            Comment:        These addresses were assigned by the IETF, the organization that develops Internet protocols, in the Best Current Practice document, RFC 1918 which can be found at:
            Comment:        http://datatracker.ietf.org/doc/rfc1918
            Ref:            https://rdap.arin.net/registry/ip/192.168.0.0
            OrgName:        Internet Assigned Numbers Authority
            OrgId:          IANA
            Address:        12025 Waterfront Drive
            Address:        Suite 300
            City:           Los Angeles
            StateProv:      CA
            PostalCode:     90292
            Country:        US
            RegDate:
            Updated:        2012-08-31
            Ref:            https://rdap.arin.net/registry/entity/IANA
            OrgTechHandle: IANA-IP-ARIN
            OrgTechName:   ICANN
            OrgTechPhone:  +1-310-301-5820
            OrgTechEmail:  abuse@iana.org
            OrgTechRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN
            OrgAbuseHandle: IANA-IP-ARIN
            OrgAbuseName:   ICANN
            OrgAbusePhone:  +1-310-301-5820
            OrgAbuseEmail:  abuse@iana.org
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN

URL: https://www.rcdprojects.org/Project/Detail/12493

Http Request:
GET /Project/Detail/12493 HTTP/1.1
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cookie: _ga=GA1.2.2051800549.1567547828
Host: www.rcdprojects.org
TE: trailers
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
upgrade-insecure-requests: 1

System.NullReferenceException: Object reference not set to an instance of an object.
   at ProjectFirmaModels.Models.ProjectStewardshipAreaTypeProjectStewardingOrganizations.GetPersonStewardOrganizations(Person person) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirmaModels\Models\ProjectStewardshipAreaType.cs:line 32
   at ProjectFirmaModels.Models.ProjectStewardshipAreaTypeProjectStewardingOrganizations.CanStewardProject(Person person, Project project) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirmaModels\Models\ProjectStewardshipAreaType.cs:line 27
   at ProjectFirma.Web.Views.Project.DetailViewData..ctor(FirmaSession currentFirmaSession, Project project, List`1 projectStages, ProjectBasicsViewData projectBasicsViewData, ProjectLocationSummaryViewData projectLocationSummaryViewData, ProjectBudgetSummaryViewData projectBudgetSummaryViewData, ProjectBudgetsAnnualViewData projectBudgetsAnnualViewData, ProjectBudgetsAnnualByCostTypeViewData projectBudgetsAnnualByCostTypeViewData, TechnicalAssistanceRequestsDetailViewData technicalAssistanceRequestDetailViewData, PerformanceMeasureExpectedSummaryViewData performanceMeasureExpectedSummaryViewData, PerformanceMeasureReportedValuesGroupedViewData performanceMeasureReportedValuesGroupedViewData, ProjectExpendituresDetailViewData projectExpendituresDetailViewData, ProjectExpendituresByCostTypeDetailViewData projectExpendituresByCostTypeDetailViewData, ImageGalleryViewData imageGalleryViewData, EntityNotesViewData projectNotesViewData, EntityNotesViewData internalNotesViewData, EntityExternalLinksViewData entityExternalLinksViewData, ProjectBasicsTagsViewData projectBasicsTagsViewData, Boolean userHasProjectAdminPermissions, Boolean userHasEditProjectPermissions, Boolean userHasProjectUpdatePermissions, Boolean userHasPerformanceMeasureActualManagePermissions, String mapFormID, String editProjectCustomAttributesUrl, String editSimpleProjectLocationUrl, String editDetailedProjectLocationUrl, String editProjectOrganizationsUrl, String editPerformanceMeasureExpectedsUrl, String editPerformanceMeasureActualsUrl, String editReportedExpendituresUrl, Boolean reportFinancialsByCostType, AuditLogsGridSpec auditLogsGridSpec, String auditLogsGridDataUrl, String editExternalLinksUrl, ProjectNotificationGridSpec projectNotificationGridSpec, String projectNotificationGridName, String projectNotificationGridDataUrl, Boolean userCanEditProposal, ProjectOrganizationsDetailViewData projectOrganizationsDetailViewData, List`1 classificationSystems, String editProjectBoundingBoxFormID, List`1 geospatialAreaTypes, DisplayProjectCustomAttributesViewData displayProjectCustomAttributeTypesViewData, ProjectContactsDetailViewData projectContactsDetailViewData, String editProjectContactsUrl, String editExpectedFundingUrl, ProjectTimelineDisplayViewData projectTimelineDisplayViewData, Boolean userHasProjectTimelinePermissions) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Views\Project\DetailViewData.cs:line 268
   at ProjectFirma.Web.Controllers.ProjectController.Detail(ProjectPrimaryKey projectPrimaryKey) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\ProjectController.cs:line 217
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)