Project Firma: Making PF more resilient to the following crash:
2019-08-20 17:05:22,602;70;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ASP._Page_Views_Shared_ExpenditureAndBudgetControls_ProjectBudgetsAnnualByCostType_cshtml.<Execute>b__2(IGrouping`2 x) in c:\sitka\ProjectFirma\wwwroot\Views\Shared\ExpenditureAndBudgetControls\ProjectBudgetsAnnualByCostType.cshtml:line 75
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at ASP._Page_Views_Shared_ExpenditureAndBudgetControls_ProjectBudgetsAnnualByCostType_cshtml.Execute() in c:\sitka\ProjectFirma\wwwroot\Views\Shared\ExpenditureAndBudgetControls\ProjectBudgetsAnnualByCostType.cshtml:line 75
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.Html.RenderPartialExtensions.RenderPartial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Views_Project_Detail_cshtml.Execute() in c:\sitka\ProjectFirma\wwwroot\Views\Project\Detail.cshtml:line 306
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Mike Jolliffe
LogonName: mike.jolliffe@sitkatech.com
PersonID: 5743
Organization: Sitka Technology Group

IP Address: 192.168.10.155
Hostname: devrig16.sitka.local
Whois Info:
            NetRange:       192.168.0.0 - 192.168.255.255
            CIDR:           192.168.0.0/16
            NetName:        PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED
            NetHandle:      NET-192-168-0-0-1
            Parent:         NET192 (NET-192-0-0-0-0)
            NetType:        IANA Special Use
            OriginAS:
            Organization:   Internet Assigned Numbers Authority (IANA)
            RegDate:        1994-03-15
            Updated:        2013-08-30
            Comment:        These addresses are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
            Comment:
            Comment:        These addresses can be used by anyone without any need to coordinate with IANA or an Internet registry.  The traffic from these addresses does not come from ICANN or IANA.  We are not the source of activity you may see on logs or in e-mail records.  Please refer to http://www.iana.org/abuse/answers
            Comment:
            Comment:        These addresses were assigned by the IETF, the organization that develops Internet protocols, in the Best Current Practice document, RFC 1918 which can be found at:
            Comment:        http://datatracker.ietf.org/doc/rfc1918
            Ref:            https://rdap.arin.net/registry/ip/192.168.0.0
            OrgName:        Internet Assigned Numbers Authority
            OrgId:          IANA
            Address:        12025 Waterfront Drive
            Address:        Suite 300
            City:           Los Angeles
            StateProv:      CA
            PostalCode:     90292
            Country:        US
            RegDate:
            Updated:        2012-08-31
            Ref:            https://rdap.arin.net/registry/entity/IANA
            OrgTechHandle: IANA-IP-ARIN
            OrgTechName:   ICANN
            OrgTechPhone:  +1-310-301-5820
            OrgTechEmail:  abuse@iana.org
            OrgTechRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN
            OrgAbuseHandle: IANA-IP-ARIN
            OrgAbuseName:   ICANN
            OrgAbusePhone:  +1-310-301-5820
            OrgAbuseEmail:  abuse@iana.org
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN

URL: https://bor.projectfirma.com/Project/Detail/13575

Http Request:
GET /Project/Detail/13575 HTTP/1.1
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.1053500681.1552604964; ASP.NET_SessionId=5qrrk0qrm0vpcads3oantgpb; BureauOfReclamation_Prod=chunks:2; grid_ck_dhtmluserNotificationsfilterVisible=0; grid_ck_dhtmluserProjectListGridfilterVisible=0; grid_ck_dhtmlprojectsGridfilterVisible=0; grid_ck_dhtmlprojectUpdateBatchfilterVisible=0; BureauOfReclamation_ProdC1=Xu48yZHg0MJWVPesk1IV5SNTQ-QFH-kAJMVLH4IEJiQTxEu43UC55DBPtuiDsq0HTfKSybITd0Qjkc7BRtV8hzcU6ZsYMKNGMruU9xc9i8hTOZkb1oGTMvVFVVpcn0QsYYlNjTazFPEepgkWJrQZxo0oO-vIpe8932oHvepCmQlZ41vVgg_z4ny5CG4wzw4ECOneKHkxrKvfvYSvOPKLY1CbBpInrNRzcI0rnJRFiW4CknD5ykM1nHcaCfEWIFK3UUuR1aqHDbZfokgCJ2uYuHodmCcbrlugxk1bOkrp2FswEv4lF6fb_jE78Cem3UZ7fqc_FxlAOTFiYaXEbxU3ZM1kz4_AgG4Y8pe96KcGMw787Oa2kJdq2yFj6w1trGbtvZCYbQVIuiGedWwln5YxrO1EL7u3FTqVODOoi3MYycghRWNXR8wJFkzKCW6YgPs88OhjqnFyuSfwHRU1M9BTE-hjV1KHQAYCKUh2hMByeoiE5kqj-ENM_aTkOcvo4V-bm2eTjUjsi__E4I9CIH1mOAMmx6vOlMaP3ZzrmGUR4F900g6ryfCginew-ebzL1WHlo7CpKWeC2C0q2bE7QfqivpRhftX49tdBSeyVTjo-0C0OEJLtbhpQL8cb1KxjXlC11oXbd6dES2OB9g5Ro_DoCkO-DoX9kdev7tpFW580ajM4UwtI-iazl1yESHPzdhnEly24r24QOJefAcaxicCVDuve5GnIVoahq8IUk9YcTKDA24DnDqXghome2McOlDfwl5VeqlL1vEo2dH25EYMCTiU6QCdGvy7Z3WG2-inDoNZfhIpIMQv9-0FwIdxu1x8xY06W9LccZB9raxjqrSZdjWlA925JyuOUMuJPRk6eTLDHf-UWQqJj3fILuyc9_khNMVmcTUyYg9lS_-f78xusR9XSf2RQRoFRJ3FMkYmJBJTXxbQkWR7_n7eIMzOFU1QYuRLRI2HG7mmsoff7KFdCJ_YdH-rNcyR8P6F4gQrn6rz4dZm-6lSQLcc5ifkhrZdH9LrpsObhwGgPhHoR_4kwaYItrTXVl7G_hCLWLeEy5IG5i1_iqYt1EcQY8r4_DUVxP0FilTq2IYd3tb-jBvRBa8tcYSolVE3HEzkDb5ds5RqLawZnSI1neXumCS0XwD68YCPRJ6gfrIhEK4wFKbLZQT36FmoJDO2YN-jlBPb7QhkCuXgje2_hJnXkxqjLiQbwLlFbHr6b2tNCRUe6Yh_HQmLSEr_sN1esrSN-aYZ500d0KnnAG11UitXbu-7uYbHUflWEz2ASnse5FfSCMDOFHJbveUTyG-zXaPEz8dK4jww_4s3eyS9jasrmnSQl3FUKpBkABcR9Lkf-D3-bUG6pYFYU6g5ucABuUfeW_SmMAshUTT34mxwDvUg0fcuO-9AGonxxX1iqGKfzBU1WRGm0juChqAI9hrIAQauzAEAUoocRnO0vVO5xnhmovmOJ-gyejim_zku0ZBjcuQUv4ufpyqUcW0U7qE1xjzbF4dqTlFmNxCRKeg8n1kRoIohiAmP5StphcDr6hSIF2TIfcYVIlM0pXcparci2r0VFlkiweF7Is9Z-_xozrLBaoFwUnZth0EDHPR693CbzRCslpj6qqVlgRYQg3IUY9uOhH2OBGM17BnM-BzE7nCQM9SgwERcDvSI5ID08dTb6gAjNd5aOL6OOeimTM2KlOewtSzmxrd_necopWbem_FCQB0VWxytrvMYW-1r3VEN6iIRnOfDoJ8rnmZZmP5qkP8dmwmtOPy0J-LbtiueZ0yNpxJG95nT9WscVD4xvTiia8CTUux0smpsc0NEG6o4QgO0k1_lOWrEgMSmNvdd6Fv3AnEIZs8W1BMEM_krP3YnBH5tHtPXfRNFQB3u2dgrdp3auJ7JQF2LlpC8MvEzljQOyoTiAwvOvlTwRw_PC83QQx6uNRQy1wbM-03z3vBfnN3fKlqWoqsoSjKYcXKHUTMkJecNnVl_1E9jVtukJWcpRV8C2G5nheopaE_w6x4caJxCSaiQbu831pJNflsYzHIruhgZy65RwtkEuJ_qRj24Od9x3NSVpYDZ8P4DGbGPcO5EypXXIyluuZMX2v7xD4NeB1uLq7vcbwF_5aYRgGBXMtvGzzq9ofpyTEaPJ2e5bhUXkrMbybjhOGcXc9a1UqymZX3jD1GDKUYyYf70k4q9nIAjeMH6d4kUTouxpC0GXeHelVKiTt8WH-CXKBle6YT_h2XlegjaFjJ-VmmXgsh7d32v44lJvTss5Mtp9b0PcAhB1AF3aZfiK7LGRKfxh3kYsATm9KULI-_L5-YOyqTBmPQI671nDZ9hloUp48pnEy54MjXEI48BKPUVibiPbpJiJnnKlkeynU3mLARAjrds00oMcO-ryBhiv5tUC0K5kh-m0asjlrYpXX1L62WCG-KzPD1BlqlSEfQ2O29AJMffxcO7LPt7JD2QLAXpDqKUO0dNe1fSjtA4SwrDTswrKE750Tid4K8nHjiciLDkvjuCYJkcJwA3atvzgDhmIDSY19rkU0H_f1_DRixNh75ukj3akbo5bAFJfCYiP8Ve2C8jKijCMRH0jJBvN2jdCyvlgqI_qWPQ0cYw3eQZfnhrxGqgajHXu5VnZS1b0uCL3y3GRmd6eyfg--Jw4Au_j1uUviuATkECC-LPTvXJ3iAO12Iz5WTsLsFyz1Eg_1slGFCGT5FHfu630GnW3wcE1YPntfDfMpwmY4SrvclsgdiDZSqH7mLi5aK1qcliksKoZ97zdPTcLN6V3bH5pFHxOvRbnCAS-ZgWkya3MBhOE25ABL3kD3uP4FG7wcv8xKI-GvD8q7bnWEFXZ5s7sge7dtOuW2zLzRE26B3tvV9kwsmKod-Wcuvv65yWKcyBsJ11FKbIFTUFEaHEJ0NJJpnMzaNxvKNe6GoH-TqJ5mBpK4XUHY7T9OG24DBN3AcQAp6zEKlc67J75P4w6C7X5E4stbCF-xt0RncupG2jIj84H6O_rDSGoGIvNm1vSDfr13Ovjoqp9AvwDHSTSTGwibmK2B-bHvPhfYSAij6vUA9OpSRthOQMqi85qVIzFGJm4j0tkx1uzHInXeJ4mR_Yf7V-yXROGZdoAYQ91Yn05NdN22W8-e0HIcL1n2-9gD7Coda-ltUfz03blJ6fgV5R1AlroXErOiFY9wPki56MOfa8dIlKldczcelSirwCYF482g7ruC4vKB2xdLjKAADiAoDlpF66gN57FVe0bDEFyf_nY5dgrcp_wMslNW7N8UNnJhHHTOWzz9lyJOc31biFGOJhHfo_RRfE3DKc4ArENE-RZF7y1mLb6teUjFR-yPw8-tnnuAtaHD-mLS6zj8D_Fe6hQhwieBK-S9-Ht9Zny138zfWU48oLmGxdanNGLw2trbq733vtJ_lZC-h3LLpPRkmBvphqMk4AnoOU_4cNaLue8xNXIh4hzE452AdxdfEeusuPKx4YYXMswZu9CvWd9lhrZv5v8xh_JnlLLOJvm8HayjUYTfLX0GAzp-hTnNZzO1i4gcfZzjI6OWj9evWHLmdczAmbs5kYaecr6iFl9lyRKseH5zjCSuyf6XOuM00oxwM7RruNtJxiyI9IZK58Zg3ZXmecGoKK7W_GTD5Noe30uMtn6pg4ykRv51vpgCiBsJg3c4ieNZG9RuULlEwPhlMYrhzgDjE5AYBEIhe6ZepFVdYjUaQMwVbOhzJnqy0p1aBS1XG9rzTbhZ7Vo3FqNwL3eopLkvqpPyw-VmHXB8gDoJzzudlqiwemM6kyV7AdmQERQYOAdMAkIPWrbfNPrQbu92Z7SaFUtbTerbauKi1pzmo-cEF4SRrr0y_q0arhoNUHLylovzGRyRPqHPpgtPDkNh9sgGpzxkHNelT_p4Wg4lN7Ofx6kPKSwHt0AbN014wYKfRQFuI47spyeaXZrbEp4lM5zJWJbmO1HJJDFhKptUiw7aBYDM6c8i9hiLtTbxu27wvIsMBaadrqJDbfejhoMzohbTCh4jHQ1SpZGtk6jT-vi41_9c-TxjE71Mia; BureauOfReclamation_ProdC2=nqgHXlyb6e-P-Y9Mw1zm6Cw0PGjUWhQM1PUElrBmZ_4qMWsqilkdolLaqZsvaICpD34kovPqujRFd3tL4BKWvGH3mLVFAiyB9pjgxEM6lFn75Q3nDrGdQ0SsK-ZdUz0fCcivZMY9uvKAnp5csFxIqP-L0PqNYxoOXmPMHz9fX0rmF38QWs-wZo29dJZBNaaTmI4cVGEMqevdgtDDYeyIipjXnst0wCDYRJ-4VjihZaH_abFvXE4avkoQEh0RmltnvdFJyf4--dP77dtdtA; grid_ck_dhtmlclassificationsGridfilterVisible=0; grid_ck_dhtmlgeospatialAreaProjectListGridfilterVisible=0; grid_ck_dhtmlfieldDefinitionsGrid=%7Cdoop%7C%7C%7C%7C%7C; grid_ck_dhtmlfundingSourceCustomAttributeTypeGridfilterVisible=0; grid_ck_dhtmlfundingSourcesGridfilterVisible=0; grid_ck_dhtmlprojectsCalendarYearExpendituresFromFundingSourceGridfilterVisible=0; grid_ck_dhtmlprojectsFundingSourceRequestsFromFundingSourceGridfilterVisible=0; grid_ck_dhtmlproposalsGridfilterVisible=0; grid_ck_dhtmlprojectCalendarYearExpendituresForOrganizationGridfilterVisible=0; grid_ck_dhtmlpendingProjectsGridfilterVisible=0
Host: bor.projectfirma.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
upgrade-insecure-requests: 1
sec-fetch-mode: navigate
sec-fetch-user: ?1
sec-fetch-site: none

System.NullReferenceException: Object reference not set to an instance of an object.
   at ASP._Page_Views_Shared_ExpenditureAndBudgetControls_ProjectBudgetsAnnualByCostType_cshtml.<Execute>b__2(IGrouping`2 x) in c:\sitka\ProjectFirma\wwwroot\Views\Shared\ExpenditureAndBudgetControls\ProjectBudgetsAnnualByCostType.cshtml:line 75
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at ASP._Page_Views_Shared_ExpenditureAndBudgetControls_ProjectBudgetsAnnualByCostType_cshtml.Execute() in c:\sitka\ProjectFirma\wwwroot\Views\Shared\ExpenditureAndBudgetControls\ProjectBudgetsAnnualByCostType.cshtml:line 75
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.Html.RenderPartialExtensions.RenderPartial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Views_Project_Detail_cshtml.Execute() in c:\sitka\ProjectFirma\wwwroot\Views\Project\Detail.cshtml:line 306
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)