ProjectFirma: Modest improvement to the following crash. At least now we can see what the error is about. I don't think it's wise to suppress this error, as it could happen in a variety of circumstances, some of which might mean something important. Here it's just a bot that lowercased when it shouldn't have. It's OK to have the non-domain name portion of a URL be case sensitive, so the bot is in the wrong here.
2019-08-28 16:40:36,658;25;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProjectFirma.Web.Security.CustomPageViewFeature.HasPermission(Person person, CustomPage contextModelObject) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Security\CustomPageViewFeature.cs:line 45
   at ProjectFirma.Web.Security.FirmaFeatureWithContextImpl`1.DemandPermission(Person person, T contextModelObject) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Security\FirmaFeatureWithContextImpl.cs:line 49
   at ProjectFirma.Web.Controllers.CustomPageController.About(String vanityUrl) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\CustomPageController.cs:line 45
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Anonymous

IP Address: 39.100.244.43
Hostname: 39.100.244.43
Whois Info:
            inetnum:        39.96.0.0 - 39.108.255.255
            netname:        ALISOFT
            descr:          Aliyun Computing Co., LTD
            descr:          5F, Builing D, the West Lake International Plaza of S&T
            descr:          No.391 Wen'er Road, Hangzhou, Zhejiang, China, 310099
            country:        CN
            admin-c:        ZM1015-AP
            tech-c:         ZM877-AP
            tech-c:         ZM876-AP
            tech-c:         ZM875-AP
            mnt-by:         MAINT-CNNIC-AP
            mnt-irt:        IRT-CNNIC-CN
            status:         ALLOCATED PORTABLE
            last-modified:  2015-02-10T00:05:56Z
            source:         APNIC
            irt:            IRT-CNNIC-CN
            address:        Beijing, China
            e-mail:         ipas@cnnic.cn
            abuse-mailbox:  ipas@cnnic.cn
            admin-c:        IP50-AP
            tech-c:         IP50-AP
            auth:           # Filtered
            remarks:        Please note that CNNIC is not an ISP and is not
            remarks:        empowered to investigate complaints of network abuse.
            remarks:        Please contact the tech-c or admin-c of the network.
            mnt-by:         MAINT-CNNIC-AP
            last-modified:  2017-11-01T08:57:39Z
            source:         APNIC
            person:         Li Jia
            address:        NO.969 West Wen Yi Road, Yu Hang District, Hangzhou
            country:        CN
            phone:          +86-0571-85022088
            e-mail:         jiali.jl@alibaba-inc.com
            nic-hdl:        ZM1015-AP
            mnt-by:         MAINT-CNNIC-AP
            last-modified:  2014-07-30T02:02:01Z
            source:         APNIC
            person:         Guoxin Gao
            address:        5F, Builing D, the West Lake International Plaza of S&T
            address:        No.391 Wen'er Road, Hangzhou City
            address:        Zhejiang, China, 310099
            country:        CN
            phone:          +86-0571-85022600
            fax-no:         +86-0571-85022600
            e-mail:         anti-spam@list.alibaba-inc.com
            nic-hdl:        ZM875-AP
            mnt-by:         MAINT-CNNIC-AP
            last-modified:  2014-07-30T01:56:01Z
            source:         APNIC
            person:         security trouble
            e-mail:         cloud-cc-sqcloud@list.alibaba-inc.com
            address:        5th,floor,Building D,the West Lake International Plaza of S&T,391#Wen???er Road
            address:        Hangzhou, Zhejiang, China
            phone:          +86-0571-85022600
            country:        CN
            mnt-by:         MAINT-CNNIC-AP
            nic-hdl:        ZM876-AP
            last-modified:  2013-07-08T02:56:02Z
            source:         APNIC
            person:         Guowei Pan
            address:        5F, Builing D, the West Lake International Plaza of S&T
            address:        No.391 Wen'er Road, Hangzhou City
            address:        Zhejiang, China, 310099
            country:        CN
            phone:          +86-0571-85022088-30763
            fax-no:         +86-0571-85022600
            e-mail:         guowei.pangw@alibaba-inc.com
            nic-hdl:        ZM877-AP
            mnt-by:         MAINT-CNNIC-AP
            last-modified:  2013-07-09T01:34:02Z
            source:         APNIC
            route:          39.96.0.0/13
            descr:          Hangzhou Alibaba Advertising Co.,Ltd.
            country:        CN
            origin:         AS37963
            mnt-by:         MAINT-CNNIC-AP
            last-modified:  2019-08-07T23:28:06Z
            source:         APNIC
            route:          39.96.0.0/13
            descr:          Alibaba (US) Technology Co., Ltd.
            country:        CN
            origin:         AS45102
            mnt-by:         MAINT-CNNIC-AP
            last-modified:  2019-08-07T23:28:05Z
            source:         APNIC

URL: https://www.clackamaspartnership.org/about/meetingsanddocuments

Http Request:
GET /about/meetingsanddocuments HTTP/1.1
Connection: Close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en;q=0.9,en-US;q=0.8
Host: www.clackamaspartnership.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

System.NullReferenceException: Object reference not set to an instance of an object.
   at ProjectFirma.Web.Security.CustomPageViewFeature.HasPermission(Person person, CustomPage contextModelObject) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Security\CustomPageViewFeature.cs:line 45
   at ProjectFirma.Web.Security.FirmaFeatureWithContextImpl`1.DemandPermission(Person person, T contextModelObject) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Security\FirmaFeatureWithContextImpl.cs:line 49
   at ProjectFirma.Web.Controllers.CustomPageController.About(String vanityUrl) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\CustomPageController.cs:line 45
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)