Alevin: Working on trying to figure out why this exception is happening:
2019-10-24 14:58:06,790;38;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at ProjectFirma.Web.Models.IRoleExtensions.GetFeaturePermissions(IRole role, Type baseFeatureType) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirma.Web\Models\IRoleExtensions.cs:line 42
   at ProjectFirma.Web.Controllers.RoleController.Detail(Int32 roleID) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirma.Web\Controllers\RoleController.cs:line 80
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Stewart Loving-Gibbard
LogonName: stewart@sitkatech.com
PersonID: 5519
Organization: Sitka Technology Group

IP Address: 192.168.10.183
Hostname: stewart.sitka.local
Whois Info:
            NetRange:       192.168.0.0 - 192.168.255.255
            CIDR:           192.168.0.0/16
            NetName:        PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED
            NetHandle:      NET-192-168-0-0-1
            Parent:         NET192 (NET-192-0-0-0-0)
            NetType:        IANA Special Use
            OriginAS:
            Organization:   Internet Assigned Numbers Authority (IANA)
            RegDate:        1994-03-15
            Updated:        2013-08-30
            Comment:        These addresses are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
            Comment:
            Comment:        These addresses can be used by anyone without any need to coordinate with IANA or an Internet registry.  The traffic from these addresses does not come from ICANN or IANA.  We are not the source of activity you may see on logs or in e-mail records.  Please refer to http://www.iana.org/abuse/answers
            Comment:
            Comment:        These addresses were assigned by the IETF, the organization that develops Internet protocols, in the Best Current Practice document, RFC 1918 which can be found at:
            Comment:        http://datatracker.ietf.org/doc/rfc1918
            Ref:            https://rdap.arin.net/registry/ip/192.168.0.0
            OrgName:        Internet Assigned Numbers Authority
            OrgId:          IANA
            Address:        12025 Waterfront Drive
            Address:        Suite 300
            City:           Los Angeles
            StateProv:      CA
            PostalCode:     90292
            Country:        US
            RegDate:
            Updated:        2012-08-31
            Ref:            https://rdap.arin.net/registry/entity/IANA
            OrgTechHandle: IANA-IP-ARIN
            OrgTechName:   ICANN
            OrgTechPhone:  +1-310-301-5820
            OrgTechEmail:  abuse@iana.org
            OrgTechRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN
            OrgAbuseHandle: IANA-IP-ARIN
            OrgAbuseName:   ICANN
            OrgAbusePhone:  +1-310-301-5820
            OrgAbuseEmail:  abuse@iana.org
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN

URL: https://bor.projectfirma.com/Role/Detail/7

Http Request:
GET /Role/Detail/7 HTTP/1.1
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cookie: _ga=GA1.2.1388638130.1545333501; ASP.NET_SessionId=h1igzekp4kecjgy4tvtszjsa; BureauOfReclamation_Prod=chunks:2; BureauOfReclamation_ProdC1=RVDz_btUigFSaWd7307lz9kE4nP7ouY2ORBB2R5ZJpH3Hn16GCieT9qvYBTDlbQyqTWkdgrTn5HPaCl5MLNhS_rwEalzq2ShQoXRP3I8pvllPzqq6cTDZjacpxnVSWXUqNdICzGa5ALyz9RiE0FqYcr6roFbrCS75u3EWVTf94UDH_v5NFr6PSPe7Hr-mphiR3Jt8mrg98cZCayAG7Y0G5AIX3hNMTEKFeBIDPDneLkkkVDw-Rly4Sxq6y9HO3QAnWp0n4AqvPrMqX5-jRJo6tvQ7yKkhwTH1_yfuPMWRHRI1M2Cz_X1-sXoPc64iEocpJKqHndrVv_aMS_pGS33W2rvU_o9dkbUG53BogbPAT-m33P5dBlknR3LSeuB3DVHxkeeCuXGr9OCjU3N6tiQ1iZiihkfv75SkeILBSGN0ooxi-qmV3aNOQhDwaGW9DYIyeE_T1I8loAWaSmaCMMon6C-5Vh6bm8ZIN2Tsd9Qi0hC8RWIe51t0RUH-QUkUR2Px1cctmVi2axb6HcnSrHVxL5653cl34zTCbf9obkRpN-dh9CKYAYaO4Eay7MRfC5xhuzAQlfeclwKBtFo-TLkUGhjQVWdt08iPHN6tGvTMhN7q6WGP-vM-xr1sYeXDxj944EzG5wDtKA_ndBjG1IokP9IzRcfHju_SSnWERr2j7eHLq3vUKD5eH3LZYwxtt-GirIZsWQAF2Jt_g9NCiAys9PKLg0Ym5Au5MQRQ8fiJReGjrLXY-zZpP4aVEJSxOus8xQTbZSDC97BAjcAmDYr2pml4Tj6NHMljoX2p5EeePhN-rtzVZ1HeY33GYpLo65Uu9twsxBJYLXf9BBA_WLVGwVcSeAbq7GsIc-ZArdF08Szj1zJClovITmt7COWIFlEHMcyjoAlOypOSqbd4CwiDe9ZoBJBzqOgFY4Xk5rTH-fHRWmgRKCv2oQeYzO2O3uV4KUu8QFFdPe-rF5B3uitWYeBEjFAEdQwBrMvZFsLXTd36DANujQLLC_A95OLAQp45u4MobVSYA3kjs1VcrMYXTCCf4yoMRghKjoBH07C8YPAaL_Q0-RHBlEfDm77qzlvH0UFxMPl6dACbnIpGkePVDeEhZ0ksvBjWGAA5i33slKk1JQMHisNn7q4RuZEUB8dS8Ds3JWv6WIcSVwE6b3hpQ8e7EzQ-BW5EtPPbiBtQH5mEslUY_f-Xppct9QRExDGpRnmhVIS3XWEUs-bx435YYd8L1KYymbgAmluRhBsxokSpgso-K78daCyIWkoVX0vL-L3zw6M3yBToxFEF6S9Lz5x9IzWMQby8ADh6fISYITC2Zv3JeBu8PZPmjvnU8B48HvkAC_Q_qCTrKYvUGUQd87sl23dlkgmOjG805XtXeoj5hm-VVtdGbsymtu52NNfHuNwFsDwMexRdJKKqeax6PNLGNgU00L4El4d5ac-rVKVTmtb-DcEWtGaWiLTIbEtKL8k-d_8xE596A4BdmlspCqjdmrrt6DtfVSPajvt3BekiM3Ina6xBomCwZ-T3Y1XQofU0ptFlEQGY8YymBtxjclTKCk2nhPI8x9D8S_eKKqT5bAWPEwqmUjgdbNCL348Mo96RF87AAArQeDgiG7jZTUm_883L_mxZUp2Uu7qzNlMcU7k7MT02bFD7bZO0z_T83T6pnIpTzCWKc8DNKnLENhZzq_nsqGwsHMg8hmNf9L5jZyAoN3Brd0n8gTJmkZ_J4K_6c2DO-M87DdmMBowm_eD-4ivlwDHZB9QnZbOKhetb8htRofJRnPLglA1YY_iglNqKdxAaheTA9TZoJGUTP9k1sBVtJogxlRSdpOmmIipN_CcjRjJMwRVEkMLWTZ5M31LLxtTJ851KtlRbv5i69w-Tf6srcMSvmsFsWt10bGhhRWNMXCPy8ml4OiWiJqQP7aICt5GHxhaPiq7XFPeWvoSm__C2-iVxCr8YX2hA3rL_hlFfX-b7PxSdbImcV4WOc7_g22EUnRGG6Z14zTr6ujeiUZPieGOl-DUYx_BcLgH6igpW2yfwRB4IAIW2q2MWRIsqa4TvCsWqvV4u7lO-ww_Eeumzp5IQyjKhs-OshUvV7Gy9hq_mPru1hq-APCsNqeAMnM7WBg-B6Ej7roMgUvZ0GKlK4HQWH5sY05ykyOKxVnjTHc2A2zOFejA6bokOnBWp5essQ7xtkiQpORo8Jp0guFdEcNL2l51syGZxeK29AngKpZM8MICcnynCa5qNZneoNzrO-ckDqspkCcyKpF69wBy6qIjvRc_45oiUH299yhctmjT9RN7kASWE7weF10ijMPEj9WlDhvVosVhtQpZQx0s_11SiOyqAdiiaLW05HJ6ge4Ua1hWamcjB0bdBo4-z0JfLu8IVqvOjkaboxEClwGhXNtiZaPTkuveJg2g0kJEHYej3lVdjIWuAfNu9-eAqy0G06NNHTrqrRwiDWdOTuZCNV7G6Wv9xhPVsQe3zNWblClv1bxTPorS5yvT93IB6Xw8_wWL-mD46MCnLYrZ-OV1Mw7h8j99U91MvwYbSSLMFOyHSKUra0KcQaxjYFZYEmY6q2NYDS9EEKP_9mROcl3R4_pXq3Xw37s2lpAO6fiuaegaYq1hEfwm4FgMSImbjzP1QJHRpwQprFBs8KxjKgS9IyT6HCNrAzVLlp7X2L_d4ru4KVH3pT9ZN4M0cF7g_kWsau-MdA5Tbte45LYfYHUjd27OoK5vbiMomGm3RE2D5FK_XndRMK3So5Z1QaxhTT6MzmrfmXK79YB1nCHlcSOsnDhVMe7vY305nWBYA4OcTDE9kJz2gMbgaDWrfgB_vLXiQUCzPSSDbkzQwx2AlFxJdATkZnfKKG1o4YyvuMRc8sSNm53pdcOXXBIjoODr-2DlX67T36qkT57pn74NLmJVGO9Jnhw3O9hq7m_u4Zr_nA8yOgphoyhhRNaPL0Pm-XLSVQeAkfqDBGKojjdfI5Xx0VZfUmbvKIbmNhG7pc2SWRp6FSsqhqSlyZWwxWUP1X5yTkc88LW2YxaNhB10LqYP031Wf-00cwiHg3tR50bMFdflZ8cQsfGhqjK-bAWfF0phMhXo7rM11olepdppaMQJecMznL24xKQ6c-YaxN_nTeDoKc4eIm9BZPnw4kmF2Mqi3tSHAVri8q-IcoySpELzda-NhMbodMaSA8BZJ4pAURQ5R1C4NiW7dJAC5ijusCp6lEvSFbxA-XG2koTeZ2B9B7y2nTktjYYseSrRboBDL2XHjY2kID7MWv0O5Q6yuIfAXU4bgw4zCVqBwwme_jMEv8GXXPQL3dVDU31jqQyDiogMTBSJqoJh6AsCZss7rH6ypY-P5P5oMWMYSMSO7bDCLvD0hcG6e4iuGrBUX_gxN6Hwpum2rrnzsT5Qs6IJE6qj5MIPKxb9pMbCeLFKp5rHuy4V5dIX2YTA3rBceWfBsBPVIq7x0DninvhuuH8xfduViiTf6si6PwVkLK7quvh16ogjKw6n2kY8VXpbdCZdgu3444Qfudeu6p9vjghA641o3RxGPOIFiW4cZcUFvEnpG0CXQVRuKN5v-5BWgPSeSaILpXFwnlA5zEGzKfA5XikvIvYN5WjvGmK6HiP-bH6KZKM31ZV7XMHwBplqxuiA24ql8bDg4F-fHBl2WYP2kAKs3gMGpNMtd17ykg_CVtp4dkghK78nxxjOT7zPtgNfULcCXmtW6VSUZYSkKf2125RCZuYiMxqKWLplBJvi3PwgW8aCFCv_0GH6jkELY7DD6gHZiAGjlqOqG5_zHjMAg3O8vVUN_gxcXLAWetINH9eYU7gfukv2kWoLD_u-hIHaP_vqMruD83YpyGkUWkRq9uZX3G9STTeRBwAdQszWxOscdmupkwE588rcPB07uhbXPxrMkipNVvJBoxblgWuh9OBQvQXD4FjuTyOBPpKoZ1Asrz78tVMqXdDIgAwA1w1qH-4605VeA5snZBGrF5ZcMp5M6AIYYol6M32uX7OjU1OtmeRB9-Pnb1XlnCHNI0w72ozIJSuooBuTooHNZOY2; BureauOfReclamation_ProdC2=mmOYIhQ12XGiGtc-rTabZr3bjuil9AQhJaOnfatm48D56_t50VzP5Or4v-snh10Ue7CSlQCFxlaU6AutHbaIVp_J00zomIVlmNKeFdKtZtKLpH6Z4mf23ve8m9zm0YKzNGqIOfc_1uYdmxWYDEKfIgUIZdLT-ifPnNwzSjaACXVnjZ3GQKcELsI7JcCuaXDNkRmvIgL9u3jsFjG_kB-in2fJ2XGgAqTqScuaYq67OkbXqlDLNrfG44m6xDsmcP6SeCVZEDwH7fFm7D9Mj2noRwQ1To4fy1g6OkDsmW9tRLTJWBYWAszazxrRe41gvH5zZG_aW8QgHBPqK29R0nUdedbUO1C6H0DXm1MVp-uQzH0R64LZJBN-QqKH_YAzGZVp10aQFBL1BLniI-zYXw
Host: bor.projectfirma.com
Referer: https://keystone.sitkatech.com/core/connect/authorize?client_id=BureauOfReclamation&redirect_uri=https%3A%2F%2Fbor.projectfirma.com%2FAccount%2FLogOn&response_mode=form_post&response_type=id_token%20token&scope=openid%20all_claims%20keystone&state=OpenIdConnect.AuthenticationProperties%3DfFJh5bTwlQHMC1seB4JDAZFCf7J_-fctEUjKh6IuWdb0w5DQ9gVGuBnvG0T-OUgO2JNX1Y9BvbNDokWlPGmIZgiCGwkCzl1JzQyowSz2HLKFFcLU05ruVBtytOKpqjU3qfPiGKDb20mnyxXIVbNyRnm61pzXB4iZSnkK5dQM58u1JXUHIEWbIlK5WZI_USIJcNDNmjY_O7gyaDqPvT4b8pvwz9gEMUxpK4JEJjGYya1xR0F9tYYgrD1QyPU-Rg2a&nonce=637075510800365367.ZTk0ZmY5YmUtMGVlYS00Y2JhLTk2OTYtN2FhZWQ1OTQ1ZDY4NzZkNzU3MzMtYjA0Yi00ZGFkLTkzYjYtZTY2MDlmMzBjZThl
TE: trailers
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
upgrade-insecure-requests: 1

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at ProjectFirma.Web.Models.IRoleExtensions.GetFeaturePermissions(IRole role, Type baseFeatureType) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirma.Web\Models\IRoleExtensions.cs:line 42
   at ProjectFirma.Web.Controllers.RoleController.Detail(Int32 roleID) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirma.Web\Controllers\RoleController.cs:line 80
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)