app alerts crash fix added a lock in CreateUninitializedItem function as it was the only function in this class without a lock on _sessionItemsBySessionIdDict.
stack trace:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at LtInfo.Common.Mvc.InMemorySessionStateStore.CreateUninitializedItem(HttpContext context, String sessionID, Int32 timeout) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\LtInfo.Common\Mvc\InMemorySessionStateStore.cs:line 162
   at System.Web.SessionState.SessionStateModule.GetSessionStateItem()
   at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)