ProjectFirma:
Attempting to track the issue below. I believe it is erratic, so this may take a few tries to track down.

2019-09-29 02:37:24,484;28;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at LtInfo.Common.GdalOgr.OgrInfoCommandLineRunner.GetExtentFromGeoJson(FileInfo ogrInfoFileInfo, String geoJson, Double totalMilliseconds) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\LtInfo.Common\GdalOgr\OgrInfoCommandLineRunner.cs:line 69
   at ProjectFirma.Web.Models.BoundingBox.MakeBoundingBoxFromGeoJson(String geoJson) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Models\BoundingBox.cs:line 195
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProjectFirma.Web.Models.BoundingBox.MakeBoundingBoxFromLayerGeoJsonList(List`1 layerGeoJsons) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Models\BoundingBox.cs:line 260
   at ProjectFirma.Web.Controllers.OrganizationController.GetMapInitJson(Organization organization, Boolean& hasSpatialData, Person person) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 219
   at ProjectFirma.Web.Controllers.OrganizationController.Detail(OrganizationPrimaryKey organizationPrimaryKey) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 169
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Anonymous

IP Address: 40.77.167.5
Hostname: msnbot-40-77-167-5.search.msn.com Whois Info:
            NetRange:       40.74.0.0 - 40.125.127.255
            CIDR:           40.125.0.0/17, 40.74.0.0/15, 40.76.0.0/14, 40.96.0.0/12, 40.80.0.0/12, 40.120.0.0/14, 40.124.0.0/16, 40.112.0.0/13
            NetName:        MSFT
            NetHandle:      NET-40-74-0-0-1
            Parent:         NET40 (NET-40-0-0-0-0)
            NetType:        Direct Assignment
            OriginAS:
            Organization:   Microsoft Corporation (MSFT)
            RegDate:        2015-02-23
            Updated:        2015-05-27
            Ref:            https://rdap.arin.net/registry/ip/40.74.0.0
            OrgName:        Microsoft Corporation
            OrgId:          MSFT
            Address:        One Microsoft Way
            City:           Redmond
            StateProv:      WA
            PostalCode:     98052
            Country:        US
            RegDate:        1998-07-09
            Updated:        2017-01-28
            Comment:        To report suspected security issues specific to traffic emanating from Microsoft online services, including the distribution of malicious content or other illicit or illegal material through a Microsoft online service, please submit reports to:
            Comment:        * https://cert.microsoft.com.
            Comment:
            Comment:        For SPAM and other abuse issues, such as Microsoft Accounts, please contact:
            Comment:        * abuse@microsoft.com.
            Comment:
            Comment:        To report security vulnerabilities in Microsoft products and services, please contact:
            Comment:        * secure@microsoft.com.
            Comment:
            Comment:        For legal and law enforcement-related requests, please contact:
            Comment:        * msndcc@microsoft.com
            Comment:
            Comment:        For routing, peering or DNS issues, please
            Comment:        contact:
            Comment:        * IOC@microsoft.com
            Ref:            https://rdap.arin.net/registry/entity/MSFT
            OrgAbuseHandle: MAC74-ARIN
            OrgAbuseName:   Microsoft Abuse Contact
            OrgAbusePhone:  +1-425-882-8080
            OrgAbuseEmail:  abuse@microsoft.com
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/MAC74-ARIN
            OrgTechHandle: MRPD-ARIN
            OrgTechName:   Microsoft Routing, Peering, and DNS
            OrgTechPhone:  +1-425-882-8080
            OrgTechEmail:  IOC@microsoft.com
            OrgTechRef:    https://rdap.arin.net/registry/entity/MRPD-ARIN

URL: https://www.rcdprojects.org/Organization/Detail/62

Http Request:
GET /Organization/Detail/62 HTTP/1.1
Cache-Control: no-cache
Connection: Keep-Alive
Pragma: no-cache
Accept: */*
Accept-Encoding: gzip, deflate
From: bingbot(at)microsoft.com
Host: www.rcdprojects.org
User-Agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at LtInfo.Common.GdalOgr.OgrInfoCommandLineRunner.GetExtentFromGeoJson(FileInfo ogrInfoFileInfo, String geoJson, Double totalMilliseconds) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\LtInfo.Common\GdalOgr\OgrInfoCommandLineRunner.cs:line 69
   at ProjectFirma.Web.Models.BoundingBox.MakeBoundingBoxFromGeoJson(String geoJson) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Models\BoundingBox.cs:line 195
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProjectFirma.Web.Models.BoundingBox.MakeBoundingBoxFromLayerGeoJsonList(List`1 layerGeoJsons) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Models\BoundingBox.cs:line 260
   at ProjectFirma.Web.Controllers.OrganizationController.GetMapInitJson(Organization organization, Boolean& hasSpatialData, Person person) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 219
   at ProjectFirma.Web.Controllers.OrganizationController.Detail(OrganizationPrimaryKey organizationPrimaryKey) in C:\Sitka\ProjectFirma\Temp\build\ProjectFirmaTrunk\ProjectFirma\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 169
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)